# Generated by Django 5.1.3 on 2024-12-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pysona", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email Address"),
        ),
    ]
