# Generated by Django 5.1.3 on 2024-12-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pysona", "0003_alter_customuser_thumbnail_persona_project_assign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persona",
            name="techsav",
            field=models.IntegerField(default=0),
        ),
    ]
