# Generated by Django 5.1.3 on 2024-12-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pysona", "0005_alter_project_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="uxboard",
            field=models.URLField(blank=True, null=True),
        ),
    ]
