# Generated by Django 5.1.3 on 2024-12-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pysona", "0006_alter_project_uxboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="complexity",
            field=models.IntegerField(default=0),
        ),
    ]
