# Generated by Django 5.1.3 on 2024-12-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pysona", "0007_project_complexity"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="type",
            field=models.CharField(default="Creative", max_length=255),
        ),
    ]
